# Site settings
baseURL = "http://fsimonmagie.com/"
languageCode = "fr-fr"
title = "Felix Simon - Magicien"
theme = "hugo-elate-theme"

[params]
  
  custom_css = []

  # Meta
  author = "Félix Simon"
  description = "Magicien & Mentaliste"
  email = "fsimon.magie@gmail.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = ""
    home = ""
    video = "Vidéo"
    work = "Prestations"
    testimonials = "Témoignages"
    services = "Services"
    about = "Marques"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Félix Simon"
    subtitle = 'Magicien & Mentaliste'
    quote = "‟L'art du magicien, parce qu’il fait croire à ce qui n’est pas, parce qu’il prend en défaut la logique et bouscule les certitudes, est la plus merveilleuse des initiations à ce dont l’homme à le plus besoin : le rêve.”" 
    author = "— Alain Decaux"
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
      img = "profile_bg.jpg"
      description = [
        """
        Félix Simon est un magicien né entre les vignes de Bourgogne. Il découvre, très jeune la magie, qui deviendra quelques années plus tard sa passion.
        C’est à l'âge de 20 ans que Félix arrive à Bruxelles avec sa mallette de magicien. 
        """,
        """
        Petit à petit, il exprime son talent jusqu'à se faire une réputation de qualité comme magicien et mentaliste. 
        En effet, c'est au contact de son public, lors d'événements que Félix aime éblouir les invités avec ses tours de cartes et de mentalisme. 
        Par ses effets et ses manipulations, il confronte les spectateurs à la surprise, leur permettant le temps d'une soirée d'être ébloui et de retrouver leur âme d'enfant.
        """,
        """
        C’est dans le close up que Félix séduit son public, le captivant par son talent, son humour, sa sympathie et sa bienveillance.
        Il saura sans aucun doute vous surprendre, vous faire croire que tout est possible et que sa magie est bien réelle. 
        """
      ]


  [params.intro.video]
    enable = true
    title = "Voir le teaser"
    icon = "icon-play2"
    url = "//www.youtube.com/watch?v=dQw4w9WgXcQ"


  # Work section
  [params.work]
    enable = true
    title = "Prestations de close-up & Mentalisme"
    description = "Le Close-up signifiant “gros plan” en Anglais est une spacialité de la prestidigitation qui consiste à se produire très près des spectateurs."

    [[params.work.row]]
      img = "/photo-1515169067868-5387ec356754.jpeg"
      alt = "Ice-breaker"
      title = "Ice-breaker"
      subtitle = ""

    [[params.work.row]]
      img = "/photo-1519225421980-715cb0215aed.jpeg"
      alt = "Mariages, Anniversaires"
      title = "Mariages, Anniversaires"
      subtitle = ""

    [[params.work.row]]
      img = "/photo-1506362802973-bd1717de901c.jpeg"
      alt = "Spectacle sur scène"
      title = "Spectacle sur scène"
      subtitle = ""

    [[params.work.row]]
      img = "/photo-1458576627435-430ad58ead3b.jpeg"
      alt = "Corporate"
      title = "Au sein de votre entreprise"
      subtitle = ""

    [[params.work.row]]
      img = "/photo-1573167507387-6b4b98cb7c13.jpeg"
      alt = "Communication non-verbale"
      title = "Communication non-verbale"
      subtitle = ""

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Ils m'ont fait confiance"
    description = "Merci blah blah blah blah blah blah blah"

    [[params.testimonials.item]]
      quote = "&ldquo;CT vrèment tré tré bien.&rdquo;"
      person = 'Jean Doe <span class="subtext">Ministre</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;J'en ai encore plein les yeux.&rdquo;"
      person = 'John Doe <span class="subtext">Retraitée</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Trop cool. &rdquo;"
      person = 'Chris Nash <span class="subtext">Chef des avions</span>'
      img = "person3.jpg"
      alt = "Person3"


  # Services section
  [params.services]
    enable = true
    title = "Photos"
    description = "Le Close-up signifiant “gros plan” en Anglais est une spacialité de la prestidigitation qui consiste à se produire très près des spectateurs."

  [[params.services.item]]
    img = "/photo-1458576627435-430ad58ead3b.jpeg"
    alt = "Séminaire"

  [[params.services.item]]
    img = "/photo-1506362802973-bd1717de901c.jpeg"
    alt = "Close-up"

  [[params.services.item]]
    img = "/photo-1573167507387-6b4b98cb7c13.jpeg"
    alt = "Conférence"

  [[params.services.item]]
    img = "/photo-1515169067868-5387ec356754.jpeg"
    alt = "Diner, gala"

  [[params.services.item]]
    img = "/photo-1519225421980-715cb0215aed.jpeg"
    alt = "Anniversaire et mariage"


  # About section
  [params.about]
    enable = true
    title = "Les marques qui m'ont fait confiance"

    [[params.about.item]]
      img = "/brands/spirito.jpg"

    [[params.about.item]]
      img = "//upload.wikimedia.org/wikipedia/commons/4/44/BMW.svg"

    [[params.about.item]]
      img = "//www.mariescorner.com/wp-content/uploads/2019/02/logoMC_420px.png"

    [[params.about.item]]
      img = "//static.latribune.fr/article_body/505822/logo-galeries.jpg"

    [[params.about.item]]
      img = "//www.luxe-infinity.com/wp-content/uploads/2020/04/louis-vuitton-logo.jpg"

    [[params.about.item]]
      img = "/brands/montaigne.png"

    [[params.about.item]]
      img = "//www.jdadijon.com/wp-content/uploads/2016/09/groupama-logo.jpg"

    [[params.about.item]]
      img = "/brands/dbb.png"

    [[params.about.item]]
      img = "/brands/imperial.png"


  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Une question ? Écrivez-moi"
    description = ""
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Félix Simon"],
        ["icon-phone", "0033/6 82 87 11 45"],
        ["icon-envelope", "fsimon.magie@gmail.com"],
      ]
    
    name = "Votre nom"
    email = "Email"
    phone = "Téléphone"
    message = "Message"
    button = "Envoyer"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Félix Simon &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; design de <a href="http://freehtml5.co/" target="_blank">freehtml5.co</a> et <a href="//github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["/social/facebook.png", "//www.facebook.com/felix.le.magicien/"],
        ["/social/instagram.png", "//www.instagram.com/felix_magie/"],
      ]
