# Site settings
baseURL = "http://fsimonmagie.com/"
languageCode = "fr-fr"
title = "Felix Simon - Magicien"
theme = "hugo-elate-theme"

[params]
  
  custom_css = []

  # Meta
  author = "Félix Simon"
  description = "Magicien & Mentaliste"
  email = "fsimon.magie@gmail.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = ""
    home = ""
    video = "Vidéo"
    work = "Prestations"
    testimonials = "Témoignages"
    services = "Services"
    about = "Marques"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Félix Simon"
    subtitle = 'Magicien & Mentaliste'
    quote = "‟L'art du magicien, parce qu’il fait croire à ce qui n’est pas, parce qu’il prend en défaut la logique et bouscule les certitudes, est la plus merveilleuse des initiations à ce dont l’homme à le plus besoin : le rêve.”" 
    author = "— Alain Decaux"
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
      img = "profile_bg.jpg"
      description = [
        """
        Félix Simon est un magicien né entre les vignes de Bourgogne. Il découvre, très jeune la magie, qui deviendra quelques années plus tard sa passion.
        C’est à l'âge de 20 ans que Félix arrive à Bruxelles avec sa mallette de magicien. 
        """,
        """
        Petit à petit, il exprime son talent jusqu'à se faire une réputation de qualité comme magicien et mentaliste. 
        En effet, c'est au contact de son public, lors d'événements que Félix aime éblouir les invités avec ses tours de cartes et de mentalisme. 
        Par ses effets et ses manipulations, il confronte les spectateurs à la surprise, leur permettant le temps d'une soirée d'être ébloui et de retrouver leur âme d'enfant.
        """,
        """
        C’est dans le close up que Félix séduit son public, le captivant par son talent, son humour, sa sympathie et sa bienveillance.
        Il saura sans aucun doute vous surprendre, vous faire croire que tout est possible et que sa magie est bien réelle. 
        """
      ]


  [params.intro.video]
    enable = true
    title = "Voir le teaser"
    icon = "icon-play2"
    url = "//www.youtube.com/watch?v=dQw4w9WgXcQ"


  # Work section
  [params.work]
    enable = true
    title = "Prestations de close-up & Mentalisme"
    # description = "Le Close-up signifiant “gros plan” en Anglais est une spacialité de la prestidigitation qui consiste à se produire très près des spectateurs."

    [[params.work.row]]
      img = "/img/conf_thumb.png"
      title = "Repas d’entreprises / Gala / Cocktail"
      subtitle = ""

    [[params.work.row]]
      img = "/img/gala.jpg"
      alt = "Réceptions / Soirées privées"
      title = "Mariages, Anniversaires"
      subtitle = ""

    [[params.work.row]]
      img = "/img/spec.jpg"
      alt = "Spectacle sur scène"
      title = "Spectacle sur scène"
      subtitle = ""

    [[params.work.row]]
      img = "/img/corpo.png"
      alt = "Corporate"
      title = "Corporate"
      subtitle = ""

    [[params.work.row]]
      img = "/img/recept.png"
      alt = "Conférence"
      title = "Conférence"
      subtitle = ""

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Ils m'ont fait confiance"
    description = "Merci blah blah blah blah blah blah blah"

    [[params.testimonials.item]]
      quote = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
      person = 'Jean Doe <span class="subtext">Ministre</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
      person = 'John Doe <span class="subtext">Retraitée</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
      person = 'Chris Nash <span class="subtext">Chef des avions</span>'
      img = "person3.jpg"
      alt = "Person3"

    [[params.testimonials.item]]
      quote = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
      person = 'Jean Doe <span class="subtext">Ministre</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
      person = 'John Doe <span class="subtext">Retraitée</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
      person = 'Chris Nash <span class="subtext">Chef des avions</span>'
      img = "person3.jpg"
      alt = "Person3"


  # Services section
  [params.services]
    enable = true
    title = "Photos"
    # description = "Le Close-up signifiant “gros plan” en Anglais est une spécialité de la prestidigitation qui consiste à se produire très près des spectateurs."

  [[params.services.item]]
    img ="/img/IMG_4751.JPG"
    thumb ="/img/IMG_4751_thumb.png"
  [[params.services.item]]
    img ="/img/IMG_4779.JPG"
    thumb ="/img/IMG_4779_thumb.png"
  [[params.services.item]]
    img ="/img/IMG_5112.jpg"
    thumb ="/img/IMG_5112_thumb.png"
  [[params.services.item]]
    img ="/img/IMG_4766.JPG"
    thumb ="/img/IMG_4766_thumb.png"
  [[params.services.item]]
    img ="/img/IMG_4757.JPG"
    thumb ="/img/IMG_4757_thumb.png"
  [[params.services.item]]
    img ="/img/IMG_4742.JPG"
    thumb ="/img/IMG_4742_thumb.png"
  [[params.services.item]]
    img ="/img/IMG_4611.JPG"
  [[params.services.item]]
    img ="/img/IMG_2627.JPG"
    thumb ="/img/IMG_2627_thumb.png"
  [[params.services.item]]
    img ="/img/IMG_4485.JPG"
    thumb ="/img/IMG_4485_thumb.png"
  [[params.services.item]]
    img ="/img/IMG_4483.JPG"
    thumb ="/img/IMG_4483_thumb.png"
  [[params.services.item]]
    img ="/img/DSC00268.jpg"
    thumb ="/img/DSC00268_thumb.png"
  [[params.services.item]]
    img ="/img/DSC00267.jpg"
    thumb ="/img/DSC00267_thumb.png"
  [[params.services.item]]
    img ="/img/DSC00233-2.jpg"
    thumb ="/img/DSC00233-2_thumb.png"
  [[params.services.item]]
    img ="/img/DSC00219.jpg"
    thumb ="/img/DSC00219_thumb.png"
  [[params.services.item]]
    img ="/img/DSC00111.jpg"
    thumb ="/img/DSC00111_thumb.png"
  [[params.services.item]]
    img ="/img/DSC00105.jpg"
    thumb ="/img/DSC00105_thumb.png"
  [[params.services.item]]
    img ="/img/DSC00045.jpg"
    thumb ="/img/DSC00045_thumb.png"
  [[params.services.item]]
    img ="/img/DSC00053.jpg"
    thumb ="/img/DSC00053_thumb.png"
  # [[params.services.item]]
  #   img ="/img/DSC00040.jpg"
  #   thumb ="/img/DSC00040_thumb.png"


  # About section
  [params.about]
    enable = true
    title = "Les marques qui m'ont fait confiance"

    [[params.about.item]]
      img = "/img/spirito.jpg"

    [[params.about.item]]
      img = "//upload.wikimedia.org/wikipedia/commons/4/44/BMW.svg"

    [[params.about.item]]
      img = "//www.mariescorner.com/wp-content/uploads/2019/02/logoMC_420px.png"

    [[params.about.item]]
      img = "//static.latribune.fr/article_body/505822/logo-galeries.jpg"

    [[params.about.item]]
      img = "//www.luxe-infinity.com/wp-content/uploads/2020/04/louis-vuitton-logo.jpg"

    [[params.about.item]]
      img = "/img/montaigne.png"

    [[params.about.item]]
      img = "//www.jdadijon.com/wp-content/uploads/2016/09/groupama-logo.jpg"

    [[params.about.item]]
      img = "/img/dbb.png"

    [[params.about.item]]
      img = "/img/imperial.png"

    [[params.about.item]]
      img = "/img/belfius.png"


  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Une question ? Écrivez-moi"
    description = ""
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Félix Simon"],
        ["icon-phone", "0033/6 82 87 11 45"],
        ["icon-envelope", "fsimon.magie@gmail.com"],
      ]
    
    name = "Votre nom"
    email = "Email"
    phone = "Téléphone"
    message = "Message"
    button = "Envoyer"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Félix Simon &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; design de <a href="http://freehtml5.co/" target="_blank">freehtml5.co</a> et <a href="//github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["/social/facebook.png", "//www.facebook.com/felix.le.magicien/"],
        ["/social/instagram.png", "//www.instagram.com/felix_magie/"],
      ]
